### ISSUE TITLE
Unexpected token = 

### ISSUE THREAD

**Issue by HugoVinicius** [coolnickname/baileys-REST#1]
Congratulations on the coolnicknam initiative

Are you using a specific version of baileys?

Because the bug fix is ​​not working.

thank you

**Comment by HugoVinicius** [comment]
My version of nodejs was out of date

**Comment by coolnickname** [comment]
I do, though. It's 1.0.1. 

I know 1.0.2 has released but it's not available on npm yet, once it is don't update because it's incompatible.
